apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  name: soundcheck-external-demo
  description: SCE Demo Component
spec:
  type: website
  lifecycle: production
  owner: toast-infra
  system: soundcheck
